import "./styles/globals.scss";

import { Inter } from "next/font/google";
import NavBar from "./components/ui/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {props.children}
        {props.modal}
      </body>
    </html>
  );
}
