import "./styles/globals.scss";
import { Roboto, Roboto_Slab } from "next/font/google";
import NavBar from "./components/ui/Navbar";
import { UserProvider } from "@auth0/nextjs-auth0/client";

const robotoFont = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: [ "300", "400", "500", "700"],
});

const robotoSlabFont = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-robotoSlab",
  weight: [ "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Next.js App Route",
  description: "Generated by create next app",
};

const someFunc = () => {let addOne; addOne+2; if(addOne > 1) return 2; }

export default function RootLayout(props) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`${robotoFont.variable} ${robotoSlabFont.variable}`} >
          <NavBar />
          {props.children}
          {props.modal}
        </body>
      </UserProvider>
    </html>
  );
}
